setwd("C:/Users/tomer/Downloads/")
library(data.table)
household_power_consumption<-unzip("exdata%2Fdata%2Fhousehold_power_consumption.zip")
household_power_consumption<-fread("household_power_consumption.txt",header=TRUE,sep=";")
household_power_consumption$Date<-as.Date(household_power_consumption$Date,format="%d/%m/%Y")
household_power_consumption$Global_active_power<-as.numeric(household_power_consumption$Global_active_power)
with(household_power_consumption,hist(Global_active_power,col="red",main ="Global Active Power",xlab = "Global Active Power(kilowalts)"))
dev.copy(png)
dev.off()