setwd("C:/Users/tomer/Downloads/")
library(data.table)
household_power_consumption<-unzip("exdata%2Fdata%2Fhousehold_power_consumption.zip")
household_power_consumption<-fread("household_power_consumption.txt",header=TRUE,sep=";")
household_power_consumption$Date<-as.Date(household_power_consumption$Date,format="%d/%m/%Y")
household_power_consumption$Global_active_power<-as.numeric(household_power_consumption$Global_active_power)
relevant_dates1<-subset(household_power_consumption,Date==c("2007-02-01"))
relevant_dates2<-subset(household_power_consumption,Date==c("2007-02-02"))
relevant_dates<-rbind(relevant_dates1,relevant_dates2)
relevant_dates[,dt:=paste(Date,Time,sep = " ")]
timeline<-as.POSIXlt(relevant_dates$dt)
par(mfcol=c(2,2),mar=c(4,4,2,1))
plot(timeline,relevant_dates$Global_active_power,type="n",ylab="Global Active Power (kilowatts)",xlab="")
lines(timeline,relevant_dates$Global_active_power)
plot(timeline,relevant_dates$Sub_metering_1,type="n",xlab="",ylab="Energy Sub Metering")
lines(timeline,relevant_dates$Sub_metering_1)
lines(timeline,relevant_dates$Sub_metering_2,col="red")
lines(timeline,relevant_dates$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty =c(1,1,1),cex=0.5)
plot(timeline,relevant_dates$Voltage,xlab="datetime",ylab="Voltage",type="n")
lines(timeline,relevant_dates$Voltage)
plot(timeline,relevant_dates$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="n")
lines(timeline,relevant_dates$Global_reactive_power)
dev.copy(png)
dev.off()


