setwd("C:/Users/tomer/Downloads/")
library(data.table)
household_power_consumption<-unzip("exdata%2Fdata%2Fhousehold_power_consumption.zip")
household_power_consumption<-fread("household_power_consumption.txt",header=TRUE,sep=";")
household_power_consumption$Date<-as.Date(household_power_consumption$Date,format="%d/%m/%Y")
household_power_consumption$Global_active_power<-as.numeric(household_power_consumption$Global_active_power)
relevant_dates1<-subset(household_power_consumption,Date==c("2007-02-01"))
relevant_dates2<-subset(household_power_consumption,Date==c("2007-02-02"))
relevant_dates<-rbind(relevant_dates1,relevant_dates2)
relevant_dates[,dt:=paste(Date,Time,sep = " ")]
timeline<-as.POSIXlt(relevant_dates$dt)
plot(timeline,relevant_dates$Global_active_power,type="n",ylab="Global Active Power (kilowatts)",xlab="")
lines(timeline,relevant_dates$Global_active_power)
dev.copy(png)
dev.off()